kind: LimitRange
apiVersion: v1
metadata:
  name: mem-limit-range
  namespace: register-api-dev
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 200m
        memory: 256Mi
